package com.example.messageapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val PrimaryLight = Color(0xFF1A3A5C)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD4E4F7)
val OnPrimaryContainerLight = Color(0xFF001D32)

val SecondaryLight = Color(0xFF3D6A95)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFC8DDF5)
val OnSecondaryContainerLight = Color(0xFF001D32)

val TertiaryLight = Color(0xFF5E5A7D)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE3DFFF)
val OnTertiaryContainerLight = Color(0xFF1A1740)

val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)

val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF111418)
val SurfaceLight = Color(0xFFF7F9FC)
val OnSurfaceLight = Color(0xFF111418)
val SurfaceVariantLight = Color(0xFFE0E7F0)
val OnSurfaceVariantLight = Color(0xFF55667A)
val OutlineLight = Color(0xFF8795A8)
val OutlineVariantLight = Color(0xFFC8D0DB)
val InverseSurfaceLight = Color(0xFF2D3136)
val InverseOnSurfaceLight = Color(0xFFEEF1F5)
val InversePrimaryLight = Color(0xFFA1C9FF)
val ScrimLight = Color(0xFF000000)
val SurfaceDimLight = Color(0xFFD7DAE0)
val SurfaceBrightLight = Color(0xFFF7F9FC)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF1F4F8)
val SurfaceContainerLight = Color(0xFFECEFF3)
val SurfaceContainerHighLight = Color(0xFFE6E9EE)
val SurfaceContainerHighestLight = Color(0xFFE0E3E8)

// Dark theme
val PrimaryDark = Color(0xFF6BA7E8)
val OnPrimaryDark = Color(0xFF001D32)
val PrimaryContainerDark = Color(0xFF004A7C)
val OnPrimaryContainerDark = Color(0xFFD4E4F7)

val SecondaryDark = Color(0xFF94B8DB)
val OnSecondaryDark = Color(0xFF001D32)
val SecondaryContainerDark = Color(0xFF285278)
val OnSecondaryContainerDark = Color(0xFFC8DDF5)

val TertiaryDark = Color(0xFFC7C0FF)
val OnTertiaryDark = Color(0xFF2F2A4D)
val TertiaryContainerDark = Color(0xFF464064)
val OnTertiaryContainerDark = Color(0xFFE3DFFF)

val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)

val BackgroundDark = Color(0xFF05080C)
val OnBackgroundDark = Color(0xFFE0E7F0)
val SurfaceDark = Color(0xFF0F1720)
val OnSurfaceDark = Color(0xFFE0E7F0)
val SurfaceVariantDark = Color(0xFF1E2936)
val OnSurfaceVariantDark = Color(0xFFA9B8CA)
val OutlineDark = Color(0xFF5C6B7D)
val OutlineVariantDark = Color(0xFF3A4554)
val InverseSurfaceDark = Color(0xFFE0E7F0)
val InverseOnSurfaceDark = Color(0xFF2D3136)
val InversePrimaryDark = Color(0xFF1A3A5C)
val ScrimDark = Color(0xFF000000)
val SurfaceDimDark = Color(0xFF0F1720)
val SurfaceBrightDark = Color(0xFF353D46)
val SurfaceContainerLowestDark = Color(0xFF05080C)
val SurfaceContainerLowDark = Color(0xFF0C131B)
val SurfaceContainerDark = Color(0xFF111820)
val SurfaceContainerHighDark = Color(0xFF1B222A)
val SurfaceContainerHighestDark = Color(0xFF262D35)
